import people01 from "@/assets/people01.png"
import people02 from "@/assets/people02.png"
import people03 from "@/assets/people03.png"
import facebook from "@/assets/facebook.svg"
import instagram from "@/assets/instagram.svg"
import linkedin from "@/assets/linkedin.svg"
import twitter from "@/assets/twitter.svg"
import airbnb from "@/assets/airbnb.png"
import binance from "@/assets/binance.png"
import coinbase from "@/assets/coinbase.png"
import dropbox from "@/assets/dropbox.png"
import send from "@/assets/Send.svg"
import shield from "@/assets/Shield.svg"
import star from "@/assets/Star.svg"
import close from "@/assets/close.svg"
import logo from "@/assets/logo.svg"
import menu from "@/assets/menu.svg"
import discount from "@/assets/Discount.svg"
import robot from "@/assets/robot.png"
import arrowUp from "@/assets/arrow-up.svg"
import apple from "@/assets/apple.svg"
import google from "@/assets/google.svg"
import bill from "@/assets/bill.png"
import card from "@/assets/card.png"

export { card, apple, google, bill, arrowUp, discount, robot, close, logo, menu, people01, people02, people03, facebook, instagram, linkedin, twitter, airbnb, binance, coinbase, dropbox, send, shield, star }
 